### ISSUE TITLE
Fixtures won't load

### ISSUE THREAD

**Issue by parijke** [etraxis/etraxis#129]
An exception occurred while executing 'INSERT INTO users (email, password,   
  fullname, description, role, settings, enabled, auth_failures, locked_until  
  , reset_token, reset_token_expires_at, account_provider, account_uid) VALUE  
  S (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["admin@example.com"  
  , "$argon2id$v=19$m=65536,t=6,p=1$\/p3RBb+wM5AS6APzgqR8pA$fes8FygG3r2NMB+wn  
  xPyeG1LvfvngCfZzh97Am294Iw", "eTraxis Admin", "Built-in administrator", "RO  
  LE_ADMIN", "{\"locale\":\"en_US\",\"theme\":\"azure\",\"timezone\":\"UTC\"}  
  ", 1, null, null, null, null, "etraxis", "58976f839d894babb79ca08f51ebf442"  
  ]:                                                                           
                                                                               
  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for colum  
  n 'password' at row 1

**Comment by webinarium** [comment]
Thank you for noticing the issue. This should work now, but please note that the project is under development and is not complete yet. Though, you definitely can deploy it locally if you'd like.

**Comment by parijke** [comment]
Can confirm it now works, the fixtures load
