### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by beaapaixao** [etraxis/etraxis#13]
I also saw on the 2 "howto" documents, that nothing is related to Dashboards, and in the tool, I just can see one dashboard in the path **"Projects-> my project -> metrics**". I want to know if is possible create more dashboards and if yes, how can I do it?

**Comment by webinarium** [comment]
Sorry, there is no such feature there yet.

**Comment by beaapaixao** [comment]
Okay, Thanks!
