### ISSUE TITLE
API routes but no interface?

### ISSUE THREAD

**Issue by parijke** [etraxis/etraxis#130]
Hi All,

Managed to install the software (demo). But after login (admin@example.com) I only can manage projects / users / groups. But there's no interface to manage issues?

With debug:router I cannot see routers to do so (only /api/ routes, but then the documentation is missing how to start up the API client (if any)

Best regards,
Paul

**Comment by webinarium** [comment]
Hi Paul,

Sorry for misleading, the project is under development. You're right - the API part is ready, the UI is just started.

If you would like, you can try an [older version](https://github.com/etraxis/etraxis-obsolete) of eTraxis, though it's quite outdated. There will be a migration from the old version when the new one is ready.

Also, you can try the older version in a cloud at [www.etraxis.com](https://www.etraxis.com/). There is a free plan for up to 5 accounts, which is enough to get whether you want to try to install it locally (or maybe the free plan is just fine for you, then you can stay in the cloud).

Best regards,
Artem
