### ISSUE TITLE
Is there some add-on that makes the control of SLA and show us dashboards on the tool?

### ISSUE THREAD

**Issue by beaapaixao** [etraxis/etraxis#133]
I need to know the SLA of each record, and i wanna know too if there is any add-on that can help me with dashboards.

**Comment by webinarium** [comment]
Sorry, not sure what is SLA in this context. There are no add-ons there, though it's always possible to write your own.

**Comment by beaapaixao** [comment]
Ok, Thanks! :)

By the way, SLA is Service level agreement, refers to issues that are their service time fulfilled.
