### ISSUE TITLE
Logon

### ISSUE THREAD

**Issue by robbiesahn** [etraxis/etraxis#14]
I have this installed and I am able to get to the login page but when I try to login the first time it fails. I don't see anywhere where what the default userid/password is
It looks like it is trying to load 2FA but I haven't even had a chance to enable this so I can't login . can you please advise

**Comment by webinarium** [comment]
Did you try the "root" login with empty password as described in the [documentation](https://github.com/etraxis/etraxis/wiki)?

P.S. Please note that this project is not actively maintained.

**Comment by robbiesahn** [comment]
![image](https://github.com/user-attachments/assets/212d0d6e-945a-4a9a-af3d-08ca84a4624e)
This is what I see and when i try root and no password I get an error. I understand that this app is no longer maintained.

**Comment by robbiesahn** [comment]
disregard. I fixed it. I didn't see anything anywhere but I moved the google2fa folder to the web root. once I did that I was able to login. thanks
