### ISSUE TITLE
Default value for Date fields not working when changing state

### ISSUE THREAD

**Issue by petrbrouzda** [etraxis/etraxis#3]
Default value for Date fields is not pre-filled correctly when changing state.
The "minimum" value is pre-filled instead.

Problem is in  records\state.php :

```
    if ($row['field_type'] == FIELD_TYPE_DATE)
    {
        $today = time();

        $row['param1'] = date_offset($today, $row['param1']);
        $row['param2'] = date_offset($today, $row['param2']);

        if (!is_null($value))
        {
            $value = ustr2int($value, $row['param1'], $row['param2']);  
        }
    }
```

There should be
 $value = date_offset($today, $value ); 
before
 $value = ustr2int($value, $row['param1'], $row['param2']);  
line.

Does it make sense to report problems on "etraxis-obsolete" at all? Does eTraxis 4 (which is in progress I see) recycle that code, or is it rewritten from scratch?

**Comment by webinarium** [comment]
Hi Petr,

Thank you for the fix, I have committed it to the repo.

Yes, it makes sense to report problems on "etraxis-obsolete". It's not 100%-reusable, but quite large part of the implementation is being considered and going to be ported into eTraxis 4. If this code contains a bug, it could be ported too.
