### ISSUE TITLE
SQL optimalization - some indexes

### ISSUE THREAD

**Issue by petrbrouzda** [etraxis/etraxis#4]
The following indexes made a big performace improvement on real-life system with Oracle DB:

create index ix_fva_comb on tbl_field_values ( value_id, field_type, is_latest, event_id );
create index ix_svl_val_l on tbl_string_values ( lower(string_value) );
create index ix_evts_comb on tbl_events ( event_id, record_id );
create index ix_rec_subj_l on tbl_records ( lower(subject), record_id  );

**Comment by webinarium** [comment]
Thank you! I have added two of these indexes ("tbl_field_values" and "tbl_events") and released them as new version 3.7.0.

I'm not sure about two other indexes ("tbl_string_values" and "tbl_records") - there are "LIKE" search on corresponding fields, so do these indexes really help?

**Comment by petrbrouzda** [comment]
Yes, indexes ix_svl_val_l and ix_rec_subj_l  works.

Oracle performs FULL_TABLE_SCAN without those indexes,
and performs FULL_INDEX_SCAN with those indexes.

FULL_INDEX_SCAN is much cheaper - both by report from EXPLAIN PLAN and by using common sense (indexes are smaller and are not stored in pages, so full scan of index is much faster - less data to be read).
And Oracle doesn't have to do "lower" function on every table value, because it is done in index before.

**Comment by webinarium** [comment]
Ok, but I would like to postpone these indexes for eTraxis 4. I use Doctrine in new version, and it makes database access layer quite different from the previous implementation - don't want to do the job twice.
