### ISSUE TITLE
SQL optimalization - record search

### ISSUE THREAD

**Issue by petrbrouzda** [etraxis/etraxis#5]
I've spend some time with "record search" optimalization.
I've found that some indexes are missing - described in issue #4 - and then I've found a strange behaviour of Oracle DB.

Function records_list (dbo/records.php) takes about 20 seconds on particular real-life data and searched text.
This functions construct a very large SQL command, which contains two parts
1) search for IDs of records which contains searched text
2) rendering output for records with that IDs

Block 1 is this:

and r.record_id in 
    (
        select r.record_id 
            from tbl_records r 
            where lower(r.subject) like '%jubel%'
.....
and lower(c.comment_body) like '%jubel%'
    )) r

If I take out the block 1 and execute it separately, it takes about 1.5 sec.
If I replace that block in original SQL command with a list of IDs returned by block 1 ... original SQL is executed within 0.5 sec.
But if I run the original command (which is created from block 1 embedded in block 2), execution time is 20 seconds.

I've checked execution plan and it seems that "whole command" is larger than Oracle optimizer can handle. So it's run in not-so-effective way with much bigger cost than running block 1 and block 2 separately.

So I rearranged records_list function - if search mode is used, there are two SQL selects instead of one. First select search for records and return a list of IDs, second select perform a field rendering.

Record search is much faster on our environment now.

The patch can be seen there:
http://lovecka.info/pb/records.txt
(I don't see a way how to insert file into issue).

**Comment by webinarium** [comment]
Thank you, Petr! I have committed these changes and released as new version 3.7.0.
